<script lang="ts">
 import { characterImage } from '@isometrico/world';
 import { graphics } from '$lib/demo/pixelart';
 import SpriteSheetPreview from '$lib/components/SpriteSheetPreview.svelte';
 let pose=$state<keyof typeof graphics.character.animations>('walk');
 let direction=$state(1);
 let variant=$state('default');
 const clip=$derived(graphics.character.animations[pose]);
 const sheet=$derived(characterImage(graphics.character,pose,variant));
</script>
<svelte:head><title>Taller de sprites · Isométrico</title></svelte:head>
<main class="workshop">
 <nav><a href="/">← Volver al mundo</a><a href="/editor">Editor de mapas →</a></nav>
 <p class="eyebrow">RECURSOS GRÁFICOS · PIXEL ART</p><h1>Taller de sprites</h1>
 <p>Edita los PNG conservando su cuadrícula y punto de apoyo. El catálogo conecta los gráficos con el escenario.</p>
 <SpriteSheetPreview />
 <section><div><h2>Personaje · 64 × 96 px por fotograma</h2><p>Una hoja por acción, con cuatro direcciones. Sentado reutiliza el primer fotograma de trabajar. El punto de apoyo está en (32, 80), medido desde la esquina superior izquierda de cada celda.</p>
 <label>Personaje <select bind:value={variant}><option value="default">Explorador</option><option value="ce936a">Lucía</option><option value="819582">Marcos</option></select></label>
 <label>Animación <select bind:value={pose}>{#each Object.keys(graphics.character.animations) as name}<option value={name}>{name}</option>{/each}</select></label>
 <label>Dirección <select bind:value={direction}>{#each graphics.character.directions as facing,i}<option value={i}>{facing.toUpperCase()}</option>{/each}</select></label>
 <p><a href={sheet} download>Descargar hoja de {pose==='sit'?'work':pose}</a> · <a href="/pixelart/templates/character-64x96.png" download>Plantilla con guías</a></p></div>
 <div class="preview">{#key `${pose}-${direction}-${variant}`}<div class="actor" style={`background-image:url(${sheet});background-position-y:-${(clip.row+direction)*96}px;--end:-${clip.frames*64}px;animation:frames ${clip.frames/clip.fps}s steps(${clip.frames}) infinite`}></div>{/key}</div></section>
 <section><div><h2>Hojas por acción</h2><p>PNG independientes, con celdas de 64 × 96 y fondo transparente. Todas las hojas tienen cuatro filas: NE ↗, SE ↘, SW ↙ y NW ↖.</p><div class="action-files">{#each Object.entries(graphics.character.animations).filter(([name])=>name!=='sit') as [name,action]}<a href={characterImage(graphics.character,name as keyof typeof graphics.character.animations,variant)} download><strong>{name}</strong><span>{action.frames} fotogramas · {action.fps} fps</span><small>{action.frames*64} × 384 px</small></a>{/each}</div><p>Para revisar otra dirección, usa el selector superior. La mochila identifica la espalda y el rostro señala el sentido de marcha.</p></div></section>
 <section><div><h2>Objetos y suelo</h2><p>Escritorio y mesa: 2 × 1 casillas. Sofá: 1 × 3. Panel: 3 × 1. Plantas, árboles y banderas: 1 × 1. Cambiar el dibujo no cambia las colisiones: la huella se configura en el editor.</p><p><a href="/pixelart/templates/object-2x1.png" download>Plantilla isométrica de objeto</a> · <a href="/pixelart/catalog.json" download>Descargar catálogo JSON</a></p></div>
 <div class="objects">{#each Object.entries(graphics.objects).filter(([id])=>!id.startsWith('pixel.chair-back-')&&id!=='pixel.chair-base'&&id!=='pixel.chair') as [id,item]}<a href={item.image} download><img src={item.image} alt={id}/><span>{id}</span></a>{/each}</div></section>
 <section><div><h2>Cómo sustituir un gráfico</h2><ol><li>Abre la hoja PNG en tu editor de píxeles y trabaja a resolución nativa.</li><li>Mantén fondo transparente, tamaño de celda y punto de apoyo. Las guías son una capa de referencia: elimínalas al exportar.</li><li>Guarda los PNG en <code>static/pixelart/</code>. Si cambias nombres, dimensiones o animaciones, actualiza <code>catalog.json</code>.</li><li>Recarga el mundo para cargar las texturas nuevas. En el editor, elige el gráfico del objeto y exporta el mapa para guardarlo.</li></ol><p>Cada acción tiene su propio PNG: idle, walk, work, talk y celebrate. En todas las hojas, las filas desde cero son NE (0), SE (1), SW (2) y NW (3). Las columnas avanzan de izquierda a derecha. Sit utiliza la columna inicial de work.</p><p>Este taller permite previsualizar y descargar recursos; la edición de píxeles se realiza en una herramienta externa.</p></div></section>
</main>
<style>
 .action-files{display:flex;flex-wrap:wrap;gap:12px;margin-top:16px}.action-files a{display:grid;gap:6px;border:1px solid #dce3d4;border-radius:8px;padding:16px;min-width:125px;text-decoration:none!important}.action-files span,.action-files small{font-size:12px}
 .workshop{max-width:1100px;margin:0 auto;padding:32px 24px 70px;color:#304535}.workshop nav{display:flex;justify-content:space-between;margin-bottom:50px}.workshop a{color:#526e37;text-decoration:underline}.eyebrow{font-size:11px;letter-spacing:2px}h1{font-size:40px;margin:14px 0}h2{font-size:21px;margin-bottom:14px}p,li{line-height:1.7;font-size:14px}section{display:flex;gap:30px;align-items:center;margin-top:28px;padding:28px;background:#fffdf5;border:1px solid #dce3d4;border-radius:12px}section>div:first-child{flex:1}label{display:inline-flex;gap:10px;align-items:center;margin:16px 16px 16px 0;font-size:13px}select{padding:8px;background:white;border:1px solid #cbd7be;border-radius:6px}.preview{width:220px;height:240px;display:grid;place-items:center;background:#dbe5ca;border-radius:8px}.actor{width:64px;height:96px;transform:scale(2);image-rendering:pixelated}.objects{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;max-width:440px}.objects a{display:grid;text-align:center;font-size:11px;gap:8px}.objects img{width:100%;max-width:128px;height:144px;object-fit:contain;image-rendering:pixelated;background:#e7eddd}ol{padding-left:20px}code{font-size:12px}@keyframes -global-frames{from{background-position-x:0}to{background-position-x:var(--end)}}@media(prefers-reduced-motion:reduce){.actor{animation:none!important}}@media(max-width:700px){section{flex-direction:column;align-items:stretch}.preview{align-self:center}h1{font-size:30px}.objects{width:100%;max-width:none;grid-template-columns:repeat(2,minmax(0,1fr))}}
</style>
