<script lang="ts">
 import {onMount} from 'svelte';import Page from '$lib/components/PlatformPage.svelte';import {request} from '$lib/platform/client';import SpriteThumbnail from '$lib/components/SpriteThumbnail.svelte';
 let tenants=$state<any[]>([]),users=$state<any[]>([]),audit=$state<any[]>([]),resources=$state<any[]>([]),name=$state(''),username=$state(''),password=$state(''),selected=$state(''),scope=$state('tenant'),message=$state(''),busy=$state(false),resetUser=$state(''),resetPassword=$state('');
 const labels:Record<string,string>={adventures:'Aventuras',published:'Publicadas',storageMB:'Recursos guardados (MB)',images:'Imágenes / mes',videos:'Vídeos / mes'};
 async function refresh(){const r=await request('/api/platform/management');tenants=r.tenants;users=r.users;audit=r.audit;if(!selected)selected=tenants[0]?.id??'';}
 async function run(fn:()=>Promise<void>){if(busy)return;busy=true;message='';try{await fn();}catch(e){message=(e as Error).message;}finally{busy=false;}}
 async function configure(body:unknown){await request('/api/platform/management',body);await refresh();message='Cambios guardados.';}
 async function loadResources(){resources=await request('/api/platform/resources?scope='+scope+(scope==='tenant'?'&tenant='+encodeURIComponent(selected):''));}
 onMount(()=>{void run(refresh);});
</script>
<Page title="Superadministración" description="Gestiona los espacios, sus administradores y los recursos compartidos.">
 {#if message}<p role="status">{message}</p>{/if}
 <section><h2>Crear espacio</h2><div class="row"><label>Nombre<input maxlength="120" bind:value={name}/></label><button disabled={busy||!name.trim()} onclick={()=>run(async()=>{await configure({action:'tenant.create',name});name='';})}>Crear espacio</button></div></section>
 {#each tenants as t}<section><h2>{t.name}</h2><small>Tenant: {t.id}</small><details><summary>Configurar permisos y límites</summary><label>Nombre<input bind:value={t.name}/></label><label class="check"><input type="checkbox" bind:checked={t.enabled}/> Espacio activo</label><div class="grid">{#each Object.keys(labels) as key}<label>{labels[key]}<input type="number" min="0" max="1000000" bind:value={t.limits[key]}/></label>{/each}</div><div class="row">{#each [['publish','Publicar aventuras'],['images','Generar imágenes'],['videos','Generar vídeos']] as [key,label]}<label class="check"><input type="checkbox" bind:checked={t.permissions[key]}/>{label}</label>{/each}</div><button disabled={busy} onclick={()=>run(()=>configure({action:'tenant.update',id:t.id,name:t.name,enabled:t.enabled,limits:t.limits,permissions:t.permissions}))}>Guardar configuración</button></details>
 {#each users.filter(u=>u.tenant_id===t.id) as u}<div class="row"><strong>{u.username}</strong><span>{u.enabled?'Activo':'Suspendido'}</span><button disabled={busy||!u.enabled||!t.enabled} onclick={()=>run(async()=>{await request('/api/auth/impersonate',{userId:u.id});location.href='/admin';})}>Entrar como</button><button disabled={busy} onclick={()=>run(()=>configure({action:'user.update',id:u.id,enabled:!u.enabled}))}>{u.enabled?'Suspender':'Activar'}</button><button disabled={busy} onclick={()=>{resetUser=u.id;resetPassword='';}}>Restablecer contraseña</button></div>{/each}
 </section>{/each}
 {#if resetUser}<section><h2>Restablecer contraseña de {users.find(u=>u.id===resetUser)?.username}</h2><label>Nueva contraseña<input type="password" autocomplete="new-password" minlength="10" bind:value={resetPassword}/></label><button disabled={busy||resetPassword.length<10} onclick={()=>run(async()=>{await configure({action:'user.password',id:resetUser,password:resetPassword});resetUser='';resetPassword='';})}>Guardar y cerrar sus sesiones</button><button onclick={()=>{resetUser='';resetPassword='';}}>Cancelar</button></section>{/if}
 <section><h2>Añadir administrador</h2><div class="grid"><label>Espacio<select bind:value={selected}>{#each tenants as t}<option value={t.id}>{t.name}</option>{/each}</select></label><label>Usuario<input autocomplete="off" bind:value={username}/></label><label>Contraseña inicial<input type="password" autocomplete="new-password" minlength="10" maxlength="256" aria-describedby="admin-password-help" bind:value={password}/><small id="admin-password-help">Entre 10 y 256 caracteres.</small>{#if password.length>0&&password.length<10}<small role="status">La contraseña debe tener al menos 10 caracteres para crear el administrador.</small>{/if}</label></div><button disabled={busy||!selected||password.length<10||!username} onclick={()=>run(async()=>{await configure({action:'user.create',tenantId:selected,username,password});username='';password='';})}>Crear administrador</button></section>
 <section><h2>Bibliotecas</h2><div class="row"><label>Ámbito<select bind:value={scope} onchange={()=>{resources=[];}}><option value="tenant">Biblioteca de un espacio</option><option value="global">Catálogo compartido</option></select></label>{#if scope==='tenant'}<label>Espacio<select bind:value={selected} onchange={()=>{resources=[];}}>{#each tenants as t}<option value={t.id}>{t.name}</option>{/each}</select></label>{/if}<button disabled={busy||scope==='tenant'&&!selected} onclick={()=>run(loadResources)}>Ver recursos</button></div><div class="grid">{#each resources as r}<article><SpriteThumbnail image={`/api/characters/library/${r.id}?image=${encodeURIComponent(r.image)}`} frame={r.frame} width={150} height={120}/><h3>{r.name}</h3><button disabled={busy} onclick={()=>run(async()=>{await request(scope==='tenant'?'/api/platform/promote':'/api/platform/withdraw-resource',{id:r.id});message=scope==='tenant'?'Copia publicada para todos los espacios.':'Retirado. Las copias existentes se conservan.';await loadResources();})}>{scope==='tenant'?'Compartir con todos':'Retirar del catálogo'}</button></article>{/each}</div></section>
 <details><summary>Actividad reciente</summary><div style="overflow-x:auto"><table><thead><tr><th>Fecha</th><th>Actor real</th><th>Actuando como</th><th>Acción</th></tr></thead><tbody>{#each audit as a}<tr><td>{new Date(a.created_at).toLocaleString()}</td><td>{a.actor_name??'Sistema'}</td><td>{a.effective_name??'—'}</td><td>{a.action}<br/><small>{a.target}</small></td></tr>{/each}</tbody></table></div></details>
</Page>
