import {describe,it,expect} from 'vitest';
import {parseAdventure,type Adventure} from '../src/lib/demo/adventure';
import {prepareOpenClosed,canPrepareOpenClosed} from '../src/lib/story/open-closed';
import {behavior,objectState,react,replaceBehavior,resolveStoryScene} from '../src/lib/story/engine';
import {emptyStory} from '../src/lib/story/types';
import {emptyInventory} from '../src/lib/demo/inventory';
const ref={mapId:'room',entityId:'chest'};
function fixture():Adventure{return parseAdventure({kind:'isometric-adventure',version:1,id:'chest-fixture',name:'Cofre',startMap:'room',maps:[{schemaVersion:1,id:'room',name:'Sala',theme:'office',width:6,height:6,spawn:{x:0,y:0},entities:[{id:'chest',label:'Cofre',kind:'object',visualId:'custom.closed',position:{x:2,y:2},size:{x:1,y:1},solid:true}]}],exits:[],catalog:[{id:'custom.closed',kind:'object',label:'Cofre cerrado',category:'office',size:{x:1,y:1}},{id:'custom.open',kind:'object',label:'Cofre abierto',category:'office',size:{x:1,y:1}}]});}
describe('open/closed authoring starter',()=>{
 it('creates valid repeatable transitions and a direct interaction without modifying its input',()=>{const a=fixture(),original=structuredClone(a),next=parseAdventure(prepareOpenClosed(a,ref)),b=behavior(next,ref)!;expect(a).toEqual(original);expect(b.states.map(s=>s.name)).toEqual(['Cerrado','Abierto']);expect(b.reactions.every(r=>!r.once)).toBe(true);expect(next.maps[0].entities[0].interaction).toEqual({label:'Abrir / cerrar',action:'story.interact',resourceId:'chest'});const first=react(next,emptyStory(),emptyInventory(),ref,'interact');expect(first.messages).toHaveLength(1);expect(objectState(next,first.progress,ref)).toBe(b.states[1].id);const second=react(next,first.progress,first.inventory,ref,'interact');expect(second.messages).toHaveLength(1);expect(objectState(next,second.progress,ref)).toBe(b.initialState);});
 it('changes only the graphic chosen for the active state, retaining identity, geometry and solidity',()=>{let a=prepareOpenClosed(fixture(),ref);const b=behavior(a,ref)!;a=parseAdventure(replaceBehavior(a,{...b,states:b.states.map((s,index)=>index?{...s,visualId:'custom.open'}:s)}));const scene=a.maps[0],closed=resolveStoryScene(a,scene,emptyStory(),emptyInventory()),r=react(a,emptyStory(),emptyInventory(),ref,'interact'),open=resolveStoryScene(a,scene,r.progress,r.inventory);expect(closed.entities[0].visualId).toBe('custom.closed');expect(open.entities[0]).toEqual({...closed.entities[0],visualId:'custom.open'});expect(scene.entities[0].visualId).toBe('custom.closed');});
 it('keeps existing modules and visibility/interactivity requirements',()=>{let a=fixture();a.maps[0].entities[0].interaction={label:'Hablar',action:'chat.open',resourceId:'existing-chat'};a=replaceBehavior(a,{...ref,states:[],reactions:[],visibility:{mode:'all',conditions:[]},blockedMessage:'Espera.'});const next=parseAdventure(prepareOpenClosed(a,ref));expect(next.maps[0].entities[0].interaction).toEqual(a.maps[0].entities[0].interaction);expect(behavior(next,ref)?.visibility).toEqual(behavior(a,ref)?.visibility);expect(behavior(next,ref)?.blockedMessage).toBe('Espera.');});
 it('does not overwrite authored states/reactions or hijack pickups and exits',()=>{const a=prepareOpenClosed(fixture(),ref);expect(canPrepareOpenClosed(a,ref)).toBe(false);expect(()=>prepareOpenClosed(a,ref)).toThrow('sin estados ni reacciones');const pick=fixture();pick.maps[0].entities[0].pickup={itemId:'key',quantity:1};expect(canPrepareOpenClosed(pick,ref)).toBe(false);const exit=fixture();exit.maps[0].entities[0].interaction={label:'Viajar',action:'adventure.exit',resourceId:'exit'};expect(canPrepareOpenClosed(exit,ref)).toBe(false);expect(canPrepareOpenClosed(fixture(),{...ref,entityId:'missing'})).toBe(false);});
 it('replaces a passive information action so the new reactions can execute',()=>{const a=fixture();a.maps[0].entities[0].interaction={label:'Examinar',action:'info.open',resourceId:'chest'};expect(prepareOpenClosed(a,ref).maps[0].entities[0].interaction?.action).toBe('story.interact');});
});
