import {describe,it,expect} from 'vitest';
import {parseAdventure,type Adventure} from '../src/lib/demo/adventure';
import {availability,allows,react,setModuleStatus,setObjectState,resolveStoryScene,restoreStory,moduleStatus,objectState,replaceBehavior} from '../src/lib/story/engine';
import {emptyStory,entityKey,moduleKey,reactionKey,type EntityBehavior} from '../src/lib/story/types';
import {emptyInventory,readInventory} from '../src/lib/demo/inventory';
import {readStory,saveStory} from '../src/lib/story/progress';
import {chatProgressKey} from '../src/lib/chat/routingtales';
import {resetProgress} from '../src/lib/demo/test-progress';
import {walkable} from '../packages/world/src/navigation';
const source={mapId:'a',entityId:'person'},target={mapId:'b',entityId:'cabinet'};
const stateBehavior:EntityBehavior={...target,initialState:'closed',states:[{id:'closed',name:'Cerrado',solid:true},{id:'open',name:'Abierto',solid:false,description:'Ahora puedes pasar.'}],reactions:[]};
function fixture():Adventure{return parseAdventure({kind:'isometric-adventure',version:1,id:'story-fixture',name:'Historia',startMap:'a',maps:[{schemaVersion:1,id:'a',name:'Origen',theme:'office',width:6,height:6,spawn:{x:0,y:0},entities:[{id:'person',label:'Lucía',kind:'person',position:{x:2,y:2},interaction:{label:'Hablar',action:'chat.open',resourceId:'lucia'}}]},{schemaVersion:1,id:'b',name:'Destino',theme:'office',width:6,height:6,spawn:{x:0,y:0},entities:[{id:'cabinet',label:'Armario',kind:'cabinet',position:{x:2,y:2},solid:false,interaction:{label:'Abrir',action:'story.interact',resourceId:'cabinet'}}]}],exits:[],items:[{id:'key',name:'Llave',description:'',stackable:true}],story:{version:1,entities:[stateBehavior,{...source,states:[],reactions:[{id:'reward',event:'module.completed',moduleId:'chat',once:true,effects:[{kind:'state',...target,stateId:'open'},{kind:'give',itemId:'key',quantity:1}]}]}]}});}
function memory():Storage{const data=new Map<string,string>();return {get length(){return data.size;},key:i=>[...data.keys()][i]??null,getItem:k=>data.get(k)??null,setItem:(k,v)=>{data.set(k,v);},removeItem:k=>{data.delete(k);},clear:()=>data.clear()};}
describe('object and module story rules',()=>{
 it('preserves adventures without story and resolves their scene without mutating it',()=>{const a=fixture();delete a.story;const parsed=parseAdventure(a),p=emptyStory(),scene=parsed.maps[0];expect(resolveStoryScene(parsed,scene,p,emptyInventory())).toEqual(scene);expect(p).toEqual(emptyStory());});
 it('evaluates all/any, negation, object states, module progress and inventory across maps',()=>{const a=fixture(),i=emptyInventory();let p=emptyStory();const condition={kind:'module' as const,...source,moduleId:'chat',status:'completed' as const};expect(allows(a,p,i,{mode:'all',conditions:[condition]})).toBe(false);p=setModuleStatus(a,p,source,'chat','completed');expect(allows(a,p,i,{mode:'any',conditions:[condition,{kind:'item',itemId:'key',quantity:1}]})).toBe(true);expect(allows(a,p,i,{mode:'all',conditions:[condition,{kind:'item',itemId:'key',quantity:1}]})).toBe(false);expect(allows(a,p,i,{mode:'all',conditions:[{kind:'object',...target,stateId:'closed'},{...condition,not:true}]})).toBe(false);expect(allows(a,p,i,{mode:'any',conditions:[]})).toBe(true);});
 it('applies cross-map consequences once, preserving original definition and progress',()=>{const a=fixture(),p=setModuleStatus(a,emptyStory(),source,'chat','completed'),i=emptyInventory(),before=structuredClone(a);const result=react(a,p,i,source,'module.completed','chat');expect(objectState(a,result.progress,target)).toBe('open');expect(result.inventory.counts.key).toBe(1);expect(result.progress.fired).toEqual([reactionKey(source,'reward')]);const again=react(a,result.progress,result.inventory,source,'module.completed','chat');expect(again.inventory.counts.key).toBe(1);expect(a).toEqual(before);expect(p.states).toEqual({});expect(i.counts).toEqual({});});
 it('allows repeat reactions and skips wrong events, modules and unmet reaction requirements',()=>{let a=fixture();const b=a.story!.entities[1];b.reactions[0].once=false;b.reactions[0].when={mode:'all',conditions:[{kind:'item',itemId:'key',quantity:1}]};a=parseAdventure(a);const i=emptyInventory(),p=emptyStory();expect(react(a,p,i,source,'interact').messages).toEqual([]);expect(react(a,p,i,source,'module.completed','other').messages).toEqual([]);expect(react(a,p,i,source,'module.completed','chat').messages).toEqual([]);i.counts.key=1;const once=react(a,p,i,source,'module.completed','chat');expect(react(a,once.progress,once.inventory,source,'module.completed','chat').inventory.counts.key).toBe(3);});
 it('rolls back all effects if consumption fails, including states and once markers',()=>{const a=fixture();a.story!.entities[1].reactions[0].effects.push({kind:'consume',itemId:'key',quantity:2});const p=emptyStory(),i=emptyInventory();expect(()=>react(a,p,i,source,'module.completed','chat')).toThrow('Necesitas');expect(p).toEqual(emptyStory());expect(i).toEqual(emptyInventory());});
 it('removes hidden objects from navigation while keeping interaction-gated objects solid',()=>{let a=fixture(),p=emptyStory(),i=emptyInventory();const b=a.story!.entities[0];b.interaction={mode:'all',conditions:[{kind:'module',...source,moduleId:'chat',status:'completed'}]};expect(availability(a,p,i,target).interactive).toBe(false);expect(walkable(resolveStoryScene(a,a.maps[1],p,i),{x:2,y:2})).toBe(false);b.visibility=b.interaction;let scene=resolveStoryScene(a,a.maps[1],p,i);expect(scene.entities).toHaveLength(0);expect(walkable(scene,{x:2,y:2})).toBe(true);p=setModuleStatus(a,p,source,'chat','completed');p=setObjectState(a,p,target,'open');scene=resolveStoryScene(a,a.maps[1],p,i);expect(scene.entities[0].description).toBe('Ahora puedes pasar.');expect(walkable(scene,{x:2,y:2})).toBe(true);});
 it('moves a blocked spawn to a free cell when a state becomes solid',()=>{const a=fixture(),scene={...a.maps[1],spawn:{x:2,y:2}};const resolved=resolveStoryScene(a,scene,emptyStory(),emptyInventory());expect(resolved.spawn).not.toEqual(scene.spawn);expect(walkable(resolved,resolved.spawn)).toBe(true);expect(scene.spawn).toEqual({x:2,y:2});});
 it('rejects states which leave no free cell for the player',()=>{const a=fixture(),map=a.maps[1];map.width=1;map.height=1;map.entities[0].position={x:0,y:0};expect(()=>resolveStoryScene(a,map,emptyStory(),emptyInventory())).toThrow('ninguna casilla libre');});
 it('keeps module identities independent of chat resource changes and object IDs map-scoped',()=>{const a=fixture(),p=setModuleStatus(a,emptyStory(),source,'chat','failed');a.maps[0].entities[0].interaction!.resourceId='marcos';expect(moduleStatus(p,source,'chat')).toBe('failed');expect(moduleStatus(p,{mapId:'b',entityId:'person'},'chat')).toBe('not-started');});
 it('rejects dangling objects, modules, states, inventory refs, malformed rules and duplicate definitions',()=>{for(const mutate of [(a:Adventure)=>{a.maps[0].entities=[];},(a:Adventure)=>{a.maps[0].entities[0].interaction=undefined;},(a:Adventure)=>{a.story!.entities[0].states.pop();},(a:Adventure)=>{a.items=[];},(a:Adventure)=>{a.story!.entities.push(a.story!.entities[0]);},(a:Adventure)=>{a.story!.entities[1].reactions[0].effects=[];}]){const a=fixture();mutate(a);expect(()=>parseAdventure(a)).toThrow('Condiciones:');}});
 it('sanitizes malformed and obsolete saved progress',()=>{const a=fixture(),p=restoreStory(a,{states:{[entityKey(target)]:'missing'},modules:{[moduleKey(source,'chat')]:'invalid'},fired:['missing']});expect(p).toEqual(emptyStory());expect(()=>setModuleStatus(a,p,source,'chat','invalid' as never)).toThrow();expect(()=>setObjectState(a,p,target,'missing')).toThrow();});
 it('persists story and inventory together, migrates legacy chats without rewarding, and resets adventure-scoped progress',()=>{const a=fixture(),storage=memory();storage.setItem(chatProgressKey(a.id,'a','person','lucia'),'success');let p=readStory(storage,a);expect(moduleStatus(p,source,'chat')).toBe('completed');expect(p.fired).toEqual([]);expect(readInventory(storage,a.id).counts).toEqual({});p=setObjectState(a,p,target,'open');saveStory(storage,a.id,p,{counts:{key:2},collected:[],unlocked:[]});saveStory(storage,'other',p,emptyInventory());expect(readStory(storage,a)).toEqual(p);resetProgress(storage,a.id);expect(readStory(storage,a)).toEqual(emptyStory());expect(storage.getItem('isometrico.story.v1:other')).not.toBeNull();});
 it('restores both stored records if the second write fails',()=>{const storage=memory(),a=fixture(),p=emptyStory(),i=emptyInventory();saveStory(storage,a.id,p,i);const original=storage.setItem;let calls=0;storage.setItem=(k,v)=>{if(++calls===2)throw Error('quota');original(k,v);};expect(()=>saveStory(storage,a.id,setObjectState(a,p,target,'open'),{...i,counts:{key:2}})).toThrow('quota');expect(readStory(storage,a)).toEqual(p);expect(readInventory(storage,a.id)).toEqual(i);});
 it('keeps authoring updates immutable',()=>{const a=fixture(),b={...stateBehavior,blockedMessage:'Necesitas la llave'};const next=replaceBehavior(a,b);expect(next.story!.entities.find(e=>entityKey(e)===entityKey(b))!.blockedMessage).toBe('Necesitas la llave');expect(a.story!.entities[0].blockedMessage).toBeUndefined();});
});
