<script lang="ts">
 import {tick,type Snippet} from 'svelte';
 import {X,Pin,PinOff} from 'lucide-svelte';
 let {id,title,subtitle='',footer,side='right',open=$bindable(false),pinned=$bindable(false),wide=false,pinnable=false,large=false,width=360,dockedWidth=320,onclose,modalWhenFloating=true,local=false,collapsed=false,inactive=false,panelAction,headerActions,children}:{id:string;title:string;subtitle?:string;footer?:Snippet;side?:'left'|'right';open?:boolean;pinned?:boolean;wide?:boolean;pinnable?:boolean;large?:boolean;width?:number;dockedWidth?:number;onclose?:()=>boolean|void;modalWhenFloating?:boolean;local?:boolean;collapsed?:boolean;inactive?:boolean;panelAction?:(node:HTMLElement)=>{destroy?:()=>void}|void;headerActions?:Snippet;children:Snippet}=$props();
 let panel=$state<HTMLElement>();
 const docked=$derived(pinned&&wide),shown=$derived(open||docked),modal=$derived(shown&&!docked&&modalWhenFloating);
 function attach(node:HTMLElement,config:{handler:typeof panelAction;enabled:boolean}){let control=config.enabled?config.handler?.(node):undefined;return {update(next:typeof config){control?.destroy?.();node.classList.remove('drag-positioned');for(const name of ['left','top','--panel-height'])node.style.removeProperty(name);control=next.enabled?next.handler?.(node):undefined;},destroy(){control?.destroy?.();}};}
 $effect(()=>{title; if(panel)panel.querySelector('.content')?.scrollTo({top:0});});
 function close(){if(onclose?.()===false)return;open=false;pinned=false;}
 function focusables(){return [...(panel?.querySelectorAll<HTMLElement>('button,input,select,textarea,a[href],summary,[tabindex="0"]')??[])].filter(el=>!el.matches(':disabled')&&!el.closest('[hidden],[inert]')&&el.getClientRects().length);}
 $effect(()=>{if(!modal||!panel)return;const previous=document.activeElement instanceof HTMLElement?document.activeElement:undefined;let active=true;void tick().then(()=>{if(active)(focusables()[0]??panel)?.focus();});return()=>{active=false;if(!shown&&previous?.isConnected)previous.focus({preventScroll:true});};});
 $effect(()=>{if(!shown&&panel?.contains(document.activeElement)){document.querySelector<HTMLElement>(`[aria-controls="${id}"]`)?.focus({preventScroll:true});}});
 function keydown(event:KeyboardEvent){if(!modal||document.querySelector('dialog[open]'))return;if(event.key==='Escape'){event.preventDefault();close();}else if(event.key==='Tab'){const targets=focusables(),first=targets[0],last=targets.at(-1);if(!first){event.preventDefault();panel?.focus();return;}if(event.shiftKey&&(document.activeElement===first||document.activeElement===panel)){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}}
</script>
<svelte:window onkeydown={keydown}/>
{#if modal}<button class="scrim" aria-label={`Cerrar ${title.toLowerCase()}`} tabindex="-1" onclick={close}></button>{/if}
<aside {id} inert={inactive} bind:this={panel} hidden={!shown} class:docked class:large class:local class:collapsed use:attach={{handler:panelAction,enabled:!docked}} class:left={side==='left'} class="panel" style:--panel-width={width+'px'} style:--panel-docked-width={dockedWidth+'px'} role={modal?'dialog':'complementary'} aria-modal={modal?'true':undefined} aria-label={title} tabindex="-1">
 <header class:panel-heading={!!panelAction}><div class="panel-title"><h2>{title}</h2>{#if subtitle}<p title={subtitle}>{subtitle}</p>{/if}</div><div class="header-actions">{#if headerActions}{@render headerActions()}{/if}{#if pinnable}<button type="button" aria-label={pinned?'Desfijar panel':'Fijar panel'} aria-pressed={pinned} title={pinned?'Desfijar catálogo':'Fijar en pantallas amplias'} onclick={()=>{pinned=!pinned;open=true;}}>{#if pinned}<PinOff size={17}/>{:else}<Pin size={17}/>{/if}</button>{/if}<button type="button" aria-label={`Cerrar ${title.toLowerCase()}`} title="Cerrar" onclick={close}><X size={18}/></button></div></header>
 <div class="content">{@render children()}</div>{#if modal&&footer}<div class="panel-footer">{@render footer()}</div>{/if}
</aside>
<style>
 .panel{box-sizing:border-box;position:fixed;top:var(--platform-bar-height,0px);bottom:0;right:0;width:var(--panel-width,360px);max-width:calc(100vw - 20px);background:#fbfcf9;border-left:1px solid #dce4d8;box-shadow:-12px 0 32px #183a3115;z-index:130;display:flex;flex-direction:column;min-height:0;color:#2b4133}.panel[hidden]{display:none}.panel.left{left:0;right:auto;width:340px;border-left:0;border-right:1px solid #dce4d8;box-shadow:12px 0 32px #183a3115}.panel.left.large:not(.docked){width:720px}.panel.local:not(.docked){position:absolute;top:0;bottom:0}.panel.collapsed{bottom:auto;height:auto}.panel:global(.drag-positioned){bottom:auto;height:min(var(--panel-height),calc(100% - 24px))}.panel.docked{position:relative;top:auto;bottom:auto;right:auto;left:auto;width:var(--panel-docked-width,320px);max-width:none;box-shadow:none;z-index:2;height:100%;border:1px solid #dce4d8;border-radius:12px;flex:none}.panel.docked.left{width:280px}header{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:12px 16px;border-bottom:1px solid #e2e8df;flex:none}h2{font-size:15px;font-weight:600;margin:0}header.panel-heading{cursor:grab;touch-action:none;user-select:none}.header-actions{cursor:default;display:flex;gap:4px;flex:none}.panel-title{min-width:0}.panel-title p{margin:4px 0 0;font-size:12px;color:#73836a;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.panel-footer{padding:12px 16px;border-top:1px solid #dce4d8;flex:none}button{display:grid;place-items:center;width:36px;height:36px;border:1px solid transparent;background:transparent;border-radius:7px;color:inherit;cursor:pointer}button:hover{background:#eaf0e4}button:focus-visible{outline:2px solid #74994e;outline-offset:2px}.content{overflow:auto;min-height:0;flex:1;padding:16px;overscroll-behavior:contain}.scrim{position:fixed;inset:var(--platform-bar-height,0px) 0 0;width:auto;height:auto;border:0;border-radius:0;background:#19332c35;backdrop-filter:blur(2px);z-index:120}
</style>
