<script lang="ts">
 import type {Snippet} from 'svelte';
 import {ArrowUpRight} from 'lucide-svelte';
 let {title,eyebrow='',description='',href,cover,coverAlt='',status='',published=false,meta='',children}:{title:string;eyebrow?:string;description?:string;href:string;cover?:string;coverAlt?:string;status?:string;published?:boolean;meta?:string;children?:Snippet}=$props();
 let failed=$state(false);
 $effect(()=>{cover;failed=false;});
</script>
<article class="adventure-card">
 <a class="cover" {href} aria-label={`Abrir ${title}`}><img src={!failed&&cover?cover:'/covers/adventure-default.svg'} alt={cover?coverAlt:''} loading="lazy" width="960" height="600" onerror={()=>failed=true}/><span class="open-icon" aria-hidden="true"><ArrowUpRight size={19}/></span>{#if status}<span class:published class="status"><i></i>{status}</span>{/if}</a>
 <div class="card-body">{#if eyebrow}<p class="eyebrow">{eyebrow}</p>{/if}<h3><a {href}>{title}</a></h3>{#if description}<p class="description">{description}</p>{/if}{#if meta}<p class="meta">{meta}</p>{/if}{#if children}<div class="card-actions">{@render children()}</div>{/if}</div>
</article>
<style>
 .adventure-card{min-width:0;border:1px solid #dce3d6;border-radius:18px;background:#fffef9;box-shadow:0 3px 12px #294a3010;transition:box-shadow .2s,transform .2s;display:flex;flex-direction:column}.adventure-card:hover{box-shadow:0 10px 28px #294a3018;transform:translateY(-3px)}.cover{display:block;position:relative;aspect-ratio:16/10;overflow:hidden;border-radius:17px 17px 0 0;background:#dce7d7}.cover img{width:100%;height:100%;object-fit:cover;display:block;transition:transform .3s}.cover:hover img{transform:scale(1.035)}.open-icon{position:absolute;top:14px;right:14px;display:grid;place-items:center;width:32px;height:32px;border-radius:50%;background:#fffefaac;color:#2c4937}.status{position:absolute;bottom:14px;left:16px;display:flex;align-items:center;gap:7px;background:#fffef5ed;padding:7px 10px;border-radius:6px;font:11px system-ui;color:#6b6c5b;font-weight:600}.status i{width:6px;height:6px;border-radius:50%;background:#b49a62}.status.published{color:#315f41}.status.published i{background:#51865a}.card-body{padding:22px;display:flex;flex-direction:column;flex:1}.eyebrow{margin:0 0 8px;font-size:10px;letter-spacing:1.4px;text-transform:uppercase;color:#6d7e69;font-weight:650}h3{font-size:23px;line-height:1.25;font-weight:600;margin:0;overflow-wrap:anywhere}h3 a{color:#293f32;text-decoration:none}.description{font-size:13px;line-height:1.65;color:#74806c;margin:12px 0 0;display:-webkit-box;-webkit-line-clamp:2;line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.meta{font-size:12px;color:#7c886f;margin:12px 0 0}.card-actions{padding-top:20px;margin-top:auto}.cover:focus-visible,h3 a:focus-visible{outline:3px solid #53794c;outline-offset:3px}@media(prefers-reduced-motion:reduce){.adventure-card,.cover img{transition:none}.adventure-card:hover,.cover:hover img{transform:none}}
</style>
